LostPointer
VK-BMSTU-QA/homework-4 pull request #4
Opened 2022-05-03 16:42 UTC by 23-yo-designer-from-san-francisco

2022-05-04 08:48 UTC, alexey-ershkov requested changes
Тесты должны проходить

![Снимок экрана 2022-05-04 в 11 27 25](https://user-images.githubusercontent.com/56301773/166649222-44b328f2-84e4-432d-927d-9e52591fde55.png)


Плюс отписал вам в ревью. Главные ошибки - не следуете паттерну pageObject,  все все от компонентов находится в common, и немного не правильно поняли идею с page

В первую очередь тесты должны быть легко читаемыми, как будто с пользователем общаешься и говоришь ему "залогинься" и он логинится, а вся логика как это происходит должна находится в Page. Соответственно логика работы с элементами страница скрыта в компонентах

2022-05-04 08:48 UTC, alexey-ershkov commented on tests/common.py
> +from urllib.parse import urljoin
По архитектуре - не следуете паттерну pageObject, должно быть разделение на страницы, для которых  есть класс с компонентами для страницы и с самой страницей. 

То есть ваш common точно нужно разбить по страницам

В тестах же использовать сам класс страницы для тестов и тесты благодаря этому будут выглядеть довольно лаконично

2022-05-04 08:48 UTC, alexey-ershkov commented on tests/main_test.py
> +
Мб все таки home или index вместо main - main зарезервированное слово, что думаете?

2022-05-04 08:48 UTC, alexey-ershkov commented on tests/main_test.py
> +
нет переноса строки в конце - пройдитесь линтером

2022-05-04 08:48 UTC, alexey-ershkov commented on tests/player_test.py
> +    def setUp(self):
то camelCase, то snake_case

2022-05-04 08:48 UTC, alexey-ershkov commented on tests/playlists_test.py
> +        self.login_page = LoginPage(self.driver)
К примеру вот такой код должен быть в page и чтобы вы по месту теста писали только self.login_page.login(), тип того, это в разы увеличит читаемость тестов

2022-05-04 08:51 UTC, 23-yo-designer-from-san-francisco commented on tests/player_test.py
> +    def setUp(self):
А это хуки, мне самому не понравилось :) но `set_up` не работает

2022-05-05 11:26 UTC, alexey-ershkov requested changes
Отписал комменты

- Приведите к единому стилю код
- Не используйте буфферные переменные, они понижают читаемость теста
- Не используйте assert-ы питона
- В некоторых тестах нет ассертов - добавьте, а то непонятно что тестируете (антипаттерн faker)

2022-05-05 11:26 UTC, alexey-ershkov commented on Login/LoginComponents.py
> +    FRONTEND_WARNINGS = '//div[@class="auth-form__invalidities form__invalidities"]'
Мб это все таки errors? А то смущает когда читаешь. Но это обсуждаемо

2022-05-05 11:26 UTC, alexey-ershkov commented on tests/home_test.py
> +        player = home_page.player
а почему сразу не обратится по месту, вы эти переменные для сокращения кода больше нигде не используете

но сокращение так себе выходит, ибо функции маленькие выходят

давайте выпилим

2022-05-05 11:26 UTC, alexey-ershkov commented on tests/favorites_test.py
> +        assert not self.favorites_page.track_list.track_is_liked(track_id)
где-то используете assert от либы тестирования, где-то такие

ассерты питона не нужно использовать, используете из тестов

2022-05-05 11:26 UTC, alexey-ershkov commented on tests/home_test.py
> +        tracks = HomePage(self.driver).tracks
опять же имхо лучше не выносить это в отдельные переменные, тогда читаемость теста будет лушче

тип не к каким-то неизвестным трекам обращаемся, а к трекам на домашней странице

тип `tracks -> home_page.tracks`

2022-05-05 11:26 UTC, alexey-ershkov commented on tests/playlists_test.py
> +        self.playlists_page.topbar.log_out()
приведите к единому виду - вы где-то заново страницу пересоздаете, а где-то в setUp это делаете

2022-05-05 11:26 UTC, alexey-ershkov commented on tests/playlists_test.py
> +        self.playlists_page.edit_window.fail_warning()
и все таки лучше на error переименовать, а то непонятно, что это ошибки в форме

2022-05-05 11:26 UTC, alexey-ershkov commented on tests/playlists_test.py
> +        self.playlists_page.edit_window.fail_warning()
плюс вопрос - где в подобных тестах assert-ы? тип тесты без тестов?

2022-05-05 12:45 UTC, frbgd commented on tests/favorites_test.py
> +        assert not self.favorites_page.track_list.track_is_liked(track_id)
Done

2022-05-05 12:47 UTC, frbgd commented on tests/playlists_test.py
> +        self.playlists_page.edit_window.fail_warning()
Сделал assert'ы

2022-05-05 12:50 UTC, frbgd commented on Login/LoginComponents.py
> +    FRONTEND_WARNINGS = '//div[@class="auth-form__invalidities form__invalidities"]'
done

2022-05-05 12:51 UTC, frbgd commented on tests/playlists_test.py
> +        self.playlists_page.edit_window.fail_warning()
done

2022-05-05 13:15 UTC, 23-yo-designer-from-san-francisco commented on tests/home_test.py
> +        tracks = HomePage(self.driver).tracks
Поправил

2022-05-05 13:15 UTC, 23-yo-designer-from-san-francisco commented on tests/home_test.py
> +        player = home_page.player
Поправил

2022-05-05 13:15 UTC, 23-yo-designer-from-san-francisco commented on tests/playlists_test.py
> +        self.playlists_page.topbar.log_out()
Доне (поправил)

2022-05-05 13:25 UTC, 23-yo-designer-from-san-francisco commented
Апрувлю тесты Алексея К.

2022-05-05 13:27 UTC, frbgd commented
Апрувлю тесты Леонида Б

2022-05-05 13:42 UTC, alexey-ershkov requested changes
еще немного комментов

2022-05-05 13:42 UTC, alexey-ershkov commented on Common/CommonComponents.py
> +        return "pause" in play.get_attribute("src")
кажется pause в константы и в целом дата атрибуты

2022-05-05 13:42 UTC, alexey-ershkov commented on Base/BasePage.py
> +        self.driver.maximize_window()
Зочем пустые __init__.py?

2022-05-05 13:42 UTC, alexey-ershkov commented on tests/player_test.py
> +        player.toggle_play()
зочем дважды?

2022-05-05 13:42 UTC, alexey-ershkov commented on tests/player_test.py
> +        player = self.home_page.player
и опять же промежуточные переменные, аргументируйте их наличие здесь и подобных местах

2022-05-05 13:44 UTC, 23-yo-designer-from-san-francisco commented on Base/BasePage.py
> +        self.driver.maximize_window()
Иначе не экспортировалось, мб я что-то не так делал

2022-05-05 13:46 UTC, 23-yo-designer-from-san-francisco commented on tests/player_test.py
> +        player.toggle_play()
Проверяем продолжение воспроизведения после паузы (play -> pause -> play)

2022-05-05 13:52 UTC, 23-yo-designer-from-san-francisco commented on tests/player_test.py
> +        player = self.home_page.player
Если несколько раз используется в функции - вводим переменную, так меньше букв тыкать :)

2022-05-05 14:11 UTC, 23-yo-designer-from-san-francisco commented on Base/BasePage.py
> +        self.driver.maximize_window()
Судя по https://stackoverflow.com/a/48804718/12169258 без `__init__.py` обходиться нужно лишь в особых случаях, так что оставим

2022-05-05 14:12 UTC, alexey-ershkov commented on tests/player_test.py
> +        player = self.home_page.player
оки

2022-05-05 14:12 UTC, alexey-ershkov commented on tests/player_test.py
> +        player.toggle_play()
оки

2022-05-05 14:12 UTC, alexey-ershkov commented on Base/BasePage.py
> +        self.driver.maximize_window()
хорошо

2022-05-05 14:29 UTC, alexey-ershkov commented
Аппрув от ментора

2022-05-22 19:47 UTC, dkotegov commented
Принято

2022-05-22 19:47 UTC, closed without merging